export const ROLES = {
  ADMIN: "admin",
  TRAINER: "trainer",
  EDUCATOR: "educator",
  PRINCIPAL: "principal",
};

export const PERMISSIONS = {
  MANAGE_USERS: [ROLES.ADMIN],
  MANAGE_ORGANIZATIONS: [ROLES.ADMIN],
  CREATE_COURSE: [ROLES.ADMIN, ROLES.TRAINER],
  EDIT_COURSE: [ROLES.ADMIN, ROLES.TRAINER],
  UPLOAD_MATERIALS: [ROLES.ADMIN, ROLES.TRAINER],
  REVIEW_SUBMISSIONS: [ROLES.ADMIN, ROLES.TRAINER],
  ASSIGN_GRADES: [ROLES.ADMIN, ROLES.TRAINER],
  VIEW_ENROLLED_EDUCATORS: [ROLES.ADMIN, ROLES.TRAINER],
  VIEW_ASSIGNED_COURSES: [ROLES.ADMIN, ROLES.TRAINER, ROLES.EDUCATOR, ROLES.PRINCIPAL],
  SUBMIT_WORK: [ROLES.EDUCATOR],
  VIEW_PROGRESS: [ROLES.EDUCATOR, ROLES.PRINCIPAL, ROLES.ADMIN],
  ASSIGN_COURSES_TO_EDUCATORS: [ROLES.PRINCIPAL, ROLES.ADMIN],
  SEND_WARNINGS: [ROLES.PRINCIPAL, ROLES.ADMIN],
};

export function hasPermission(role, permission) {
  if (!role || !permission) return false;
  return PERMISSIONS[permission]?.includes(role) || false;
}